DemoMVC/Controllers/DaiLyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoMVC.Data;
using DemoMVC.Models.Entities.DaiLy;
using DemoMVC.Models.Process;
using OfficeOpenXml;

namespace DemoMVC.Controllers
{
    public class DaiLyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ExcelProcess _excelProcess = new ExcelProcess(); // Khởi tạo đối tượng ExcelProcess để xử lý file Excel

        public DaiLyController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DaiLy
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.DaiLies.Include(d => d.HeThongPhanPhoi);
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: DaiLy/ImportExcel
        public async Task<IActionResult> Upload()
        {
            // Trả về View Upload để người dùng có thể tải lên file Excel
            return View("Create");
        }
        // Action UploadFile (xử lý việc tải lên file Excel và chuyển đổi thành DataTable)
        [HttpPost]
        [ValidateAntiForgeryToken] //đảm bảo tính bảo mật của hệ thống
        public async Task<IActionResult> Upload(IFormFile file)
        {
            // Kiểm tra xem file có được chọn hay không
            // Nếu không có file được chọn, thêm lỗi vào ModelState để hiển thị thông
            if (file != null)
            {
                
                string fileExtension = Path.GetExtension(file.FileName);
                // Kiểm tra định dạng file tải lên
                // Nếu file không phải là định dạng Excel (.xls hoặc .xlsx), thêm lỗi vào
                if (fileExtension != ".xls" && fileExtension != ".xlsx")
                {
                    ModelState.AddModelError("", "Please choose excel file to upload");

                }
                else
                {
                    // Tạo đường dẫn lưu file Excel

                    var fileName = DateTime.Now.ToString("yyyyMMddHHmmss") + fileExtension;
                    var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excel", fileName);
                    var fileLocation = new FileInfo(filePath).ToString();
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        // Lưu file vào thư mục Uploads/Excel
                        // Sử dụng IFormFile để lưu trữ file tải lên
                        await file.CopyToAsync(stream);
                        // Chuyển đổi file Excel thành DataTable
                        // Sử dụng phương thức ExcelToDataTable từ lớp ExcelProcess để chuyển đổi
                        var dt = _excelProcess.ExcelToDataTable(fileLocation);
                        // Kiểm tra xem DataTable có dữ liệu hay không
                        for (int i = 0; i < dt.Rows.Count; i++)
                        {
                            // Tạo đối tượng Person từ DataTable
                            var dl = new DaiLy();
                            // Gán giá trị từ DataTable vào các thuộc tính của Person
                            dl.MaDaiLy = dt.Rows[i][0].ToString();
                            dl.TenDaiLy = dt.Rows[i][1].ToString();
                            dl.DiaChi = dt.Rows[i][2].ToString();
                            dl.NguoiDaiDien = dt.Rows[i][3].ToString();
                            dl.DienThoai = dt.Rows[i][4].ToString();
                            dl.MaHTPP = dt.Rows[i][5].ToString();
                            // Thêm đối tượng Person vào CSDL
                            _context.Add(dl);
                        }
                        // Lưu thay đổi vào CSDL
                        await _context.SaveChangesAsync();
                        // Chuyển hướng về Action Index để hiển thị danh sách Person
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View("Create");
        }
                // Action Download (trả về file Excel cho người dùng tải xuống)
        public IActionResult Download()
        {
            // Tạo file Excel từ dữ liệu trong CSDL và trả về file cho người dùng tải xuống
            // Sử dụng thư viện EPPlus để tạo file Excel
            var fileName = "YourFileName" + ".xlsx";
            // Tạo một đối tượng ExcelPackage để làm việc với file Excel
            // ExcelPackage là lớp chính của thư viện EPPlus để tạo và thao tác với file
            using (ExcelPackage excelPackage = new ExcelPackage())
            {
                // Tạo một worksheet mới trong file Excel
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("Sheet1");
                // Đặt tiêu đề cho các cột trong worksheet
                // Các cột này sẽ tương ứng với các thuộc tính của Person
                worksheet.Cells["A1"].Value = "MaDaiLy";
                worksheet.Cells["B1"].Value = "TenDaiLy";
                worksheet.Cells["C1"].Value = "DiaChi";
                worksheet.Cells["D1"].Value = "NguoiDaiDien";
                worksheet.Cells["E1"].Value = "DienThoai";
                worksheet.Cells["F1"].Value = "MaHTPP";
                // Lấy danh sách Daily từ CSDL và nạp vào worksheet
                // Sử dụng _context để truy vấn dữ liệu từ bảng Persons
                var dailyList = _context.DaiLies.ToList();
                // Sử dụng LoadFromCollection để nạp dữ liệu từ danh sách Person vào worksheet
                // Dữ liệu sẽ được nạp từ hàng thứ 2 (A2) trở đi
                worksheet.Cells["A2"].LoadFromCollection(dailyList);
                // Định dạng các cột trong worksheet
                // Đặt độ rộng cho các cột để hiển thị đầy đủ dữ liệu
                var stream = new MemoryStream(excelPackage.GetAsByteArray());
                // Đặt tên file và trả về file Excel cho người dùng tải xuống
                // Sử dụng File để trả về file Excel với kiểu MIME là application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                // MemoryStream được sử dụng để lưu trữ dữ liệu của file Excel trong bộ nhớ
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
            }
        }

        // GET: DaiLy/Details/
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var daiLy = await _context.DaiLies
                .Include(d => d.HeThongPhanPhoi)
                .FirstOrDefaultAsync(m => m.MaDaiLy == id);
            if (daiLy == null)
            {
                return NotFound();
            }

            return View(daiLy);
        }

        // GET: DaiLy/Create
        public IActionResult Create()
        {
            var last = _context.DaiLies.OrderByDescending(x => x.MaDaiLy).FirstOrDefault();
            var lastId = last == null ? "DL000" : last.MaDaiLy;
            var newId = new AutoGenerateCode().GenerateId(lastId);

             ViewData["MaHTPP"] = new SelectList(_context.HeThongPhanPhois, "MaHTPP", "TenHTPP", null);

            var daily = new DaiLy
            {
                MaDaiLy = newId
            };

            return View(daily);
        }

        // POST: DaiLy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDaiLy,TenDaiLy,DiaChi,NguoiDaiDien,DienThoai,MaHTPP")] DaiLy daiLy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(daiLy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaHTPP"] = new SelectList(_context.HeThongPhanPhois, "MaHTPP", "TenHTPP", daiLy.MaHTPP);

            return View(daiLy);
        }

        // GET: DaiLy/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var daiLy = await _context.DaiLies.FindAsync(id);
            if (daiLy == null)
            {
                return NotFound();
            }
            ViewData["MaHTPP"] = new SelectList(_context.HeThongPhanPhois, "MaHTPP", "MaHTPP", daiLy.MaHTPP);
            return View(daiLy);
        }

        // POST: DaiLy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaDaiLy,TenDaiLy,DiaChi,NguoiDaiDien,DienThoai,MaHTPP")] DaiLy daiLy)
        {
            if (id != daiLy.MaDaiLy)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(daiLy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DaiLyExists(daiLy.MaDaiLy))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaHTPP"] = new SelectList(_context.HeThongPhanPhois, "MaHTPP", "TenHTPP", daiLy.MaHTPP);

            return View(daiLy);
        }

        // GET: DaiLy/Delete/5

DemoMVC/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoMVC.Data;
using DemoMVC.Models.Entities;
using X.PagedList;

namespace DemoMVC.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employee
        [AllowAnonymous] // Cho phép truy cập không cần xác thực
        // Sử dụng phân trang với thư viện X.PagedList để hiển thị dữ liệu theo trang
        public async Task<IActionResult> Index(int? page, int? pageSize)
        {
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem { Text = "3", Value = "3" },
                new SelectListItem { Text = "5", Value = "5" },
                new SelectListItem { Text = "10", Value = "10" },
                new SelectListItem { Text = "15", Value = "15" },
                new SelectListItem { Text = "25", Value = "25" },
                new SelectListItem { Text = "50", Value = "50" }
            };
            int pagesize = (pageSize ?? 3); // Lấy kích thước trang từ tham số pageSize, nếu không có thì mặc định là 3
            ViewBag.psize = pagesize; // Lưu kích thước trang vào ViewBag để sử dụng trong View

            var model = _context.Employees.ToList().ToPagedList(page ?? 1, pagesize); // Lấy danh sách Employee từ CSDL mà không theo dõi thay đổi

            return View(model);
        }

        // GET: Employee/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employee/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FirstName,LastName,Address,DateOfBirth,Position,Email,HireDate")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employee/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeeId,FirstName,LastName,Address,DateOfBirth,Position,Email,HireDate")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }
    }
}

DemoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoMVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HeThongPhanPhoi" asp-action="Index">HeThongPhanPhoi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DaiLy" asp-action="Index">DaiLy</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <form class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" method="post">
                                        <button type="submit" class="btn btn-link p-0 m-0 align-baseline">Logout</button>
                                    </form>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/ChangePassword">Change Password</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DemoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>